name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Code Quality (Ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff Check
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

  test:
    name: Run Tests (Pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Pytest
        run: uv run pytest
